w4d5/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands, only: [:index, :create, :new, :edit,
  :show, :update, :destroy]
end

w4d5/MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w4d5/MusicApp/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true
end

w4d5/MusicApp/app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true, presence: true
  validates :session_token, uniqueness: true, presence: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, pw)
    user = User.find_by(email: email)
    user && user.is_password?(pw) ? user : nil
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end
end

w4d5/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :login!, :current_user, :logged_in?

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    return nil unless session[:session_token]
    @current_user = User.find_by(session_token: session[:session_token])
  end

  def logout!
    user = current_user
    if user
      user.reset_session_token!
      session[:session_token] = nil
    end
    redirect_to new_session_url
  end

  def logged_in?
    !!current_user
  end
end

w4d5/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    band = Band.new(band_params)
    if band.save
      redirect_to band_url(band.id)
    else
      flash.now[:errors] = band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update

  end

  def destroy

  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

w4d5/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email], params[:user][:password] )
    if user
      session[:session_token] = user.reset_session_token!
      redirect_to user_url(user.id)
    else
      flash.now[:errors] = ['Invalid email/password']
      render :new
    end
  end

  def destroy
    logout!
  end
end

w4d5/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login!(user)
      redirect_to user_url(user.id)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

w4d5/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
  type='hidden'
  name='authenticity_token'
  value='#{form_authenticity_token}'/>".html_safe
  end
end

w4d5/MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

w4d5/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

w4d5/MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

w4d5/MusicApp/app/views/bands/edit.html.erb
<%= render 'shared/errors' %>
<h2>Edit Band</h2>
<br>
<form action="<%= band_url(@band.id) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label for="name">Name of Band:
    <input type="text" name="band[name]" value="<%= @band.name %>">
  </label>
  <input type="submit" value="Submit">
</form>

w4d5/MusicApp/app/views/bands/index.html.erb
<h2>Bands</h2>

<% Band.all.each do |band| %>

<ul>
  <li><a href="<%= band_url(band.id) %>"><%= band.name %></a></li>
</ul>

<%end%>

w4d5/MusicApp/app/views/bands/new.html.erb
<%= render 'shared/errors' %>
<h2>New Band</h2>
<br>
<form action="<%= bands_url %>" method="post">
  <%= auth_token %>
  <label for="name">Name of Band:
    <input type="text" name="band[name]" value="">
  </label>
  <input type="submit" value="Submit">
</form>

w4d5/MusicApp/app/views/bands/show.html.erb
<h2><%= @band.name %></h2>

w4d5/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:black;color:#00ffff;">
    <header>
      <font size="16" color="#C73F22" face="comic sans MS">MusicApp</font>
    </header>

    <% if logged_in? %>
    <form action="<%= session_url %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <%= auth_token %>
      <input type="submit" value="Logout">
    </form>
    <% else %>
    <form action="<%= new_user_url %>" method="get">
      <%= auth_token %>
      <input type="submit" value="Sign-up">
    </form>
    <form action="<%= new_session_url %>" method="get">
      <%= auth_token %>
      <input type="submit" value="Login">
    </form>
    <% end %>
    <br>

    <%= yield %>

  </body>
</html>

w4d5/MusicApp/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  <br>
<% end %>

w4d5/MusicApp/app/views/shared/_form.html.erb
<%
if from == :signup
  action_url = users_url
elsif from == :login
  action_url = session_url
end
%>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>

  <label for="user_email">Email:
    <input type="text" id="user_email" name="user[email]" value="">
  </label>
  <br>

  <label for="user_password">Password:
    <input type="password" id="user_password" name="user[password]" value="">
  </label>
  <br>

  <input type="submit" value="Submit">
</form>

w4d5/MusicApp/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'shared/errors'%>

<%= render 'shared/form', from: :signup %>

w4d5/MusicApp/app/views/users/show.html.erb
<h1>Welcome, <%= current_user.email %></h1>
<br>